variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: runner
  POSTGRES_HOST_AUTH_METHOD: trust
  ARTIFACT_TARGET: /tmp/artifacts
  REGUSER: runner
  SUPERUSER: runner
  PGPORT: 5432
  MAHOUTHOME: /builds/cbbrowne/mahout
  PGCMPHOME: /builds/cbbrowne/mahout/pgcmp
  PGBINDIR: /usr/lib/postgresql/12/bin
  PG_CONTAINER: $CI_REGISTRY_IMAGE/my-custom-postgres:latest
  PG_HOST: postgres

services:
  - name: $PG_CONTAINER
    alias: custompg
  - name: postgres
  - name: docker:19.03.1-dind

stages:
  - builddocker
  - build
  - test
  - release
  - deploy

builddocker:
  image: docker:19.03.1
  stage: builddocker
  services:
    - docker:19.03.1-dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $PG_CONTAINER docker
  - docker push $PG_CONTAINER

build-pgcmp:
  stage: build
  script:
    - gem install org-ruby
    - make all
  
connect-test:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $PG_CONTAINER
  stage: test
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
    - $PG_CONTAINER
    - $PG_HOST
  script:
    - apk add postgresql-client
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - which psql
    - psql -h $PG_HOST -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
    - psql -h $PG_HOST -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "show port;"
    - psql -h $PG_HOST -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "show config_file;"
    - psql -h $PG_HOST -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "show unix_socket_directories;"
    - psql -d "host=${PG_HOST} user=runner port=5432 dbname=${POSTGRES_DB}" -c "select 'OK' as query_from_connstring;"
    
functional-test:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $PG_CONTAINER
  stage: test
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
    - $PG_CONTAINER
    - $PG_HOST
  script:
    - apk add postgresql-client
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - export PGUSER=$POSTGRES_USER
    - export PGPORT=5432
    - export PGHOST=$PG_HOST
    - echo "running tests"
    - (cd /builds/cbbrowne/pgcmp/test; PGUSER=$POSTGRES_USER ./run-tests.sh)
